### ISSUE TITLE
Mapping sprint goal to team and sprint, not only sprint

### ISSUE THREAD

**Issue by Speeedy01** [keesschollaart81/vsts-sprint-goal#12]
If you create multiple Teams on the same sprint cycle it is not possible to define a sprint Goal per Team.

**Comment by mevanecek** [comment]
I'm curious if any progress has been made on this. With the hierarchical nature of Sprints in VSTS, many teams will be sharing the same Sprints. The Sprint Goal therefore shows up the same for all teams, although each team is going to have its own Sprint Goal.
