### ISSUE TITLE
When I set a goal for a shared iteration it sets it for other teams

### ISSUE THREAD

**Issue by msmith046** [keesschollaart81/vsts-sprint-goal#13]
Defect: a teams goals write into other teams goals with shared iterations where goal is empty on other teams

Scenario: Set goal on future shared sprint populates other teams goal when empty
Given I have shared iterations in Team 1, Team 2
And I can see Goal for future sprint for Team 1 and Team 2 is empty
When I set enter "Test goal" in Goal on future sprint for Team 1
Then I open future sprint for Team 2 I see "Test goal" in Goal

I think it should work like this

Scenario: Set goal on future shared sprint does not populates other teams goal when empty
Given I have shared iterations in Team 1, Team 2
And I can see Goal for future sprint for Team 1 and Team 2 is empty
When I set enter "Test goal" in Goal on future sprint for Team 1
Then I open future sprint for Team 2 I see Goal is empty

**Comment by namrathaj** [comment]
Hey Guys, Any Update on the fix of the above mentioned issue. We would like to have this extension at the earliest. 

Also kindly fix the performance issue.

**Comment by namrathaj** [comment]
Hi Kees,

I still see the issue mentioned by Martin.
When two teams use the same iteration, the goal of one team is getting reflected into other. Please fix this at the earliest.
