### ISSUE TITLE
Option to opt-out of telemetry

### ISSUE THREAD

**Issue by calebcartwright** [keesschollaart81/vsts-sprint-goal#21]
Would you consider adding functionality to allow users to opt out of the telemetry gathering?

**Comment by scal1024** [comment]
This is a good question. In an enterprise environment critical data is saved within the tool. So, opting out of telemetry is essential (or at least anonymizing that no conclusions can be drawn on persons/projects/companies/content).

**Comment by keesschollaart81** [comment]
Just added this with v5.0.0

**Comment by calebcartwright** [comment]
Awesome! Thanks so much @keesschollaart81
