### ISSUE TITLE
Goal Details with Dark Theme not readable

### ISSUE THREAD

**Issue by AxxiD** [keesschollaart81/vsts-sprint-goal#39]
When using the dark theme in Azure DevOps (online) the text of the goal details text is black and therefore not readable

![image](https://user-images.githubusercontent.com/1340283/63253633-82ead880-c272-11e9-96b4-3c2ba0843a6f.png)

(I've selected some of the text in the box)

**Comment by nielsams** [comment]
We reproduce this issue too.

**Comment by keesschollaart81** [comment]
Fixed in 5.1 which is now in ACC, within one week this fix will go live

**Comment by keesschollaart81** [comment]
Fixed in 5.2 which I just released

**Comment by keesschollaart81** [comment]
1,5 year later, hehe

**Comment by AxxiD** [comment]
One minor thing - the icon for emojies is still black

![grafik](https://user-images.githubusercontent.com/1340283/109422054-3b521a80-79da-11eb-8f05-2c6e3bbb741e.png)
