### ISSUE TITLE
Add widget for showing sprint goal on dashboard

### ISSUE THREAD

**Issue by pascalberger** [keesschollaart81/vsts-sprint-goal#7]
It would be nice to have also a widget for showing the sprint goal on a dashboard

**Comment by piamrozek** [comment]
I agree. Preferably a widget that can show sprint goals of all teams in one dashboard.

**Comment by keesschollaart81** [comment]
Working on it. Almost finished, I'll push it to the beta-testers ±next week.

**Comment by keesschollaart81** [comment]
Just released it. I'll leave the issue open because I'd like to add some extra features to this:
- Select the team
- Remove the title if you want to
- Make the background-flag an svg so that if will be the same color as the text

**Comment by KenBurns0128** [comment]
Apologies If I'm posting in the wrong place:
Downloaded v3 and it shows Sprint Goal in Work area and I can create Goals and they display correctly. When I select the widget for Dashboard get this error :
![sprint goal](https://user-images.githubusercontent.com/37179620/37149556-5c9f6c6a-22c6-11e8-890f-f89ae26ab112.PNG)

TFS Extensions shows no outstanding actions. TFS Version 15.117.26714.0

**Comment by KenBurns0128** [comment]
Please ignore the above post I just went back into TFS and its now correctly showing the Widget with the Sprint Goal... Thx
